name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Build for macOS (M1)
        run: |
          GOOS=darwin GOARCH=arm64 go build -trimpath -ldflags "-X main.version=${GITHUB_REF_NAME}" -o licokit-darwin-arm64 .
          shasum -a 256 licokit-darwin-arm64 > licokit-darwin-arm64.sha256

      - name: Upload binaries as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: |
            licokit-darwin-arm64
            licokit-darwin-arm64.sha256

      - name: Create a Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "licokit-darwin-arm64,licokit-darwin-arm64.sha256"
          tag: ${{ github.ref_name }}
